---
# tasks file for splunk
# === Install
- name: Download Splunk Tarball
  ansible.builtin.get_url:
    url: "{{ splunk_link }}"
    dest: "/tmp/{{ splunk_tarball_name: }}"
    mode: "0664"

- name: Unarchive Splunk Tarball
  ansible.builtin.unarchive:
    src: "/tmp/{{ splunk_tarball_name: }}"
    dest: /opt/
    remote_src: yes
# ===

- name: Ensure group "splunk" exists
  ansible.builtin.group:
    name: splunk
    state: present

- name: Create a user 'splunk' with a home directory
  ansible.builtin.user:
    name: splunk
    group: splunk
    create_home: yes

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /opt/splunk
    state: directory
    recurse: yes
    owner: splunk
    group: splunk

- name: Enable Splunk boot-start
  ansible.builtin.command: /opt/splunk/bin/splunk enable boot-start --accept-license --answer-yes --no-prompt
  become: yes
  environment:
    SPLUNK_HOME: /opt/splunk
    PATH: "/opt/splunk/bin:{{ ansible_env.PATH }}"

- name: Ensure user-seed.conf exists
  copy:
    dest: /opt/splunk/etc/system/local/user-seed.conf
    content: |
      [user_info]
      USERNAME = {{USERNAME}}
      PASSWORD = {{PASSWORD}}

- name: Start Splunk for the first time
  command: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt
  args:
    creates: /opt/splunk/var/run/splunk/splunkd.pid
