services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx/gogs.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gogs1
      - gogs2
    networks:
      - backend

  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    networks:
      - backend

  gogs1:
    image: gogs-v3
    container_name: gogs1
    restart: unless-stopped
    expose:
      - "22"
      - "3000"
    ports:
      - "22:22"
    env_file:
      - .env
    volumes:
      - ./data/gogs:/data
    depends_on:
      - db
    networks:
      - backend

  gogs2:
    image: gogs-v3
    container_name: gogs2
    restart: unless-stopped
    expose:
      - "22"
      - "3000"
    env_file:
      - .env
    volumes:
      - ./data/gogs:/data
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
