services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/gogs.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gogs1
      - gogs2
    networks:
      - backend

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./env/db.env
    networks:
      - backend

  gogs1:
    image: my-go-app
    restart: unless-stopped
    expose:
      - "3000"
      - "22"
    volumes:
      - ./data:/data
      - ./data/gogs/conf/app.ini:/data/gogs/conf/app.ini:ro
    env_file:
      - ./env/gogs.env
    depends_on:
      - db
    networks:
      - backend

  gogs2:
    image: my-go-app
    restart: unless-stopped
    expose:
      - "3000"
      - "22"
    volumes:
      - ./data:/data
      - ./data/gogs/conf/app.ini:/data/gogs/conf/app.ini:ro
    depends_on:
      - db
    env_file:
      - ./env/gogs.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
