---
# defaults file for nginx

# Список пакетів, що потрібні для додавання репозиторію Nginx
nginx_repo_prereq_packages:
  - curl
  - gnupg2
  - ca-certificates
  - lsb-release
  - ubuntu-keyring

# URL-адреса ключа та шлях для keyring
nginx_signing_key_url: "https://nginx.org/keys/nginx_signing.key"
nginx_keyring_path: "/usr/share/keyrings/nginx-archive-keyring.gpg"

# URL та компоненти репозиторію
nginx_apt_repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx"

nginx_apt_repo_filename: "nginx"

# Шаблон для pinning-у
nginx_pinning_content: |
  Package: *
  Pin: origin nginx.org
  Pin: release o=nginx
  Pin-Priority: 900
nginx_pinning_dest: "/etc/apt/preferences.d/99nginx"
# Пакети, що треба встановити після додавання репозиторію
nginx_packages:
  - nginx
  - nginx-module-otel
# {{ groups['gogs'] }} з інвентаря
