---
# roles/otel/handlers/main.yml

- name: Reload systemd and restart OTel Collector
  ansible.builtin.systemd:
    name: "{{ otel_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: true

