---
# tasks/cleanup_default_conf.yml

- name: Check if default nginx config exists
  ansible.builtin.stat:
    path: /etc/nginx/conf.d/default.conf
  register: default_nginx_conf

- name: Remove default nginx config
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  when: default_nginx_conf.stat.exists