---
- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Deploy custom haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
    owner: root
    group: root

- name: Ensure HAProxy is enabled and started
  systemd:
    name: haproxy
    state: started
    enabled: yes