---
# tasks/main.yml

- name: Install prerequisite packages for Nginx repo
  import_tasks: install_packages.yml

- name: Set up Nginx APT repository
  import_tasks: repo_setup.yml

- name: Install Nginx and additional packages
  import_tasks: install_nginx.yml

- name: Remove default nginx.conf if exists
  import_tasks: cleanup_default_conf.yml

- name: Gather Gogs IP addresses from inventory
  import_tasks: gather_gogs_ips.yml

- name: Install HAProxy and deploy configuration
  import_tasks: install_haproxy.yml

- name: Deploy Nginx configuration (nginx.conf and gogs.conf)
  import_tasks: deploy_configs.yml
