all:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: /home/vagrant/id_rsa

gogs:
  hosts:
    192.168.128.32:
    192.168.128.33:

psql:
  hosts:
    192.168.128.29:
  vars:
    ansible_host: 192.168.128.29

nginx:
  hosts:
    192.168.128.30:

splunk:
  hosts:
    192.168.128.21:

nfs:
  hosts:
    192.168.128.28: