services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/gogs.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gogs1
      - gogs2
    networks:
      - backend

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: gogs
      POSTGRES_USER: gogs
      POSTGRES_PASSWORD: gogs_pass
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend

  gogs1:
    image: my-go-app
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: gogs
      DB_USER: gogs
      DB_PASS: gogs_pass
    expose:
      - "3000"
      - "22"
    volumes:
      - ./data:/data
      - ./data/gogs/conf/app.ini:/data/gogs/conf/app.ini:ro
    depends_on:
      - db
    networks:
      - backend

  gogs2:
    image: my-go-app
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: gogs
      DB_USER: gogs
      DB_PASS: gogs_pass
    expose:
      - "3000"
      - "22"
    volumes:
      - ./data:/data
      - ./data/gogs/conf/app.ini:/data/gogs/conf/app.ini:ro
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
