---
- name: Add all target hosts to known_hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Add target host key to known_hosts
      ansible.builtin.known_hosts:
        path: "~/.ssh/known_hosts"
        name: "{{ inventory_hostname }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + inventory_hostname) }}"
      delegate_to: localhost
