---
- name: Setup Nginx Reverse Proxy Server
  hosts: nginx
  become: yes

  roles:
    - role: firewall
      vars:
        firewall_additional_service_ports:
          - { port: 80, proto: tcp }
          - { port: 443, proto: tcp }
          - { port: 2222, proto: tcp }
    - role: nginx
    - role: otel
