---
- name: Setup Splunk otel collector
  hosts:
    - gogs
    - nginx
    - psql
    - nfs
  become: yes
  roles:
    # - role: firewall
    #   vars:
    #     firewall_additional_service_ports:
    #       - { port: 4317, proto: tcp }
    #       - { port: 4318, proto: tcp }
    - role: otel
