---
- name: Setup Gogs Server
  hosts: gogs
  become: yes

  roles:
    - role: firewall
      vars:
        firewall_additional_service_ports:
          - { port: 3000, proto: tcp }
          - { port: 2049, proto: tcp }
          - { port: 2049, proto: udp }
          - { port: 111, proto: tcp }
          - { port: 111, proto: udp }
    - role: gogs
    - role: otel
