---
- name: Setup Splunk Server
  hosts: splunk
  become: yes

  roles:
    - role: firewall
      vars:
        firewall_additional_service_ports:
          - { port: 8000, proto: tcp }
          - { port: 8088, proto: tcp }
    - role: splunk
