---
- name: Setup PostgreSQL Server
  hosts: psql
  become: true

  roles:
    - role: firewall
      vars:
        firewall_additional_service_ports:
          - { port: 5432, proto: tcp }
    - role: psql
    - role: otel
