---
# roles/gogs/defaults/main.yml

# === Required variables  ===
# URL to the Gogs archive
gogs_tarball: "https://github.com/gogs/gogs/releases/download/v0.13.2/gogs_0.13.2_linux_amd64.tar.gz"

# Version/archive name (used to construct path: /tmp/{{ gogs_archive_name }})
gogs_archive_name: "gogs_0.13.2_linux_amd64.tar.gz"

# === Core paths and directories ===
gogs_user: "git"
gogs_group: "git"
gogs_user_comment: "Gogs"

# Home directory for extracting Gogs
gogs_home_dir: "/home/git"

# Path to the extracted Gogs directory (e.g., /home/git/gogs-<version>)
# If the archive extracts into a "gogs" folder, use: "{{ gogs_home_dir }}/gogs"
# Depends on how the tarball is packaged
gogs_dir: "{{ gogs_home_dir }}/gogs"

# Temporary directory for storing the archive
gogs_archive_tmp_dir: "/tmp"

# Final path to the archive
gogs_archive_tmp_path: "{{ gogs_archive_tmp_dir }}/{{ gogs_archive_name }}"

# Systemd unit name (service name)
gogs_service_name: "gogs"

# Database host address
psql_ip: "{{ groups['psql'][0] }}"

# Database credentials
postgres_gogs_db_name: "{{ vault_postgres_gogs_db_name }}"
postgres_gogs_user_name: "{{ vault_postgres_gogs_user_name }}"
postgres_gogs_user_password: "{{ vault_postgres_gogs_user_password }}"

# Local directory for storing repositories if NFS is not used
gogs_default_data_root: "/home/git/gogs-repositories"

# === NFS configuration ===
install_nfs_client: true
nfs_package_name: "nfs-common"
nfs_mount_point: "/mnt/gogs-repositories"
nfs_server: "192.168.128.28"
nfs_export: "/srv/gogs-repositories"

# Mount options (fstype - nfs, opts - rw,sync, etc.)
nfs_mount_opts: "rw,sync"

# Whether to add the mount to /etc/fstab for persistence
nfs_mount_fstab: true

# === Other settings ===
# Path to the directory containing custom Gogs config
gogs_custom_conf_dir: "{{ gogs_dir }}/custom/conf"

# Template name for app.ini (used in tasks/setup_custom_conf.yml)
gogs_app_ini_template: "app.ini.j2"

# Permissions for newly created directories
gogs_dir_mode: "0755"
