---
# defaults/main.yml

postgresql_packages:
  - python3-psycopg2
  - postgresql
  - acl
  - postgresql-client

postgresql_conf_file: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
postgresql_hba_file: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
postgres_version: "14"

# Database credentials
postgres_gogs_db_name: "{{ vault_postgres_gogs_db_name }}"
postgres_gogs_user_name: "{{ vault_postgres_gogs_user_name }}"
postgres_gogs_user_password: "{{ vault_postgres_gogs_user_password }}"
