
extensions:
  docker_observer:
    endpoint: unix:///var/run/docker.sock
    excluded_images: ['splunk']
    timeout: 15s

receivers:
#======================================
# NGINX TRACES AND METRICS
#======================================
  otlp/traces:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  nginx:
    endpoint: "http://nginx:11180/status"
    collection_interval: 60s

#======================================
# POSTGRESQL METRICS
#======================================
  postgresql:
    endpoint: db:5432
    username: "${POSTGRES_OTEL_USER}"
    password: "${POSTGRES_OTEL_PASSWORD}"
    databases:
      - "${POSTGRES_GOGS_DB}"
    collection_interval: 10s
    tls:
      insecure: true
      insecure_skip_verify: true 

#======================================
# DOCKER CONTAINERS METRICS
#======================================
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 10s
    timeout: 10s
    excluded_images:
      - "splunk/splunk:9.4"    
      - "jenkins/jenkins"    
    metrics:
      container.uptime:
        enabled: true
      container.cpu.usage.system:
        enabled: false
      container.memory.total_rss:
        enabled: true
      container.cpu.utilization:
        enabled: true
      container.memory.percent:
        enabled: true
      container.network.io.usage.rx_bytes:
        enabled: true
      container.network.io.usage.tx_bytes:
        enabled: true
      container.network.io.usage.rx_dropped:
        enabled: true
      container.network.io.usage.tx_dropped:
        enabled: true
      container.memory.usage.limit:
        enabled: true
      container.memory.usage.total:
        enabled: true
      container.blockio.io_service_bytes_recursive:
        enabled: true      
  filelog:
    include:
      - /var/lib/docker/containers/*/*.log
    include_file_name: false
    include_file_path: true
    operators:
    - type: json_parser
      if: body matches "^{.*}$"
      parse_to: attributes
      output: parse_container_name
    - id: recombine
      type: recombine
      combine_field: body
      is_first_entry: body matches "^\\d{4}-\\d{2}-\\d{2}T\\d{2}"
    - type: regex_parser
      id: parse_container_name
      regex: '(?P<container_name>.+)'
      parse_from: attributes.attrs.tag

processors:
  batch:
  resourcedetection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["dns", "os"]  

exporters:
  splunk_hec/traces:
    token: "${SPLUNK_HEC_TRACES_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
    source: "otel_traces"
    index: "traces"
    tls:
      insecure_skip_verify: true
  splunk_hec/metrics:
    token: "${SPLUNK_HEC_METRICS_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
    source: "otel_metrics"
    index: "metrics"
    tls:
      insecure_skip_verify: true
  splunk_hec/logs:
    token: "${SPLUNK_HEC_LOGS_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
    source: "otel_logs"
    index: "logs"
    tls:
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [otlp/traces]
      processors: [batch, resourcedetection/docker]
      exporters: [splunk_hec/traces]

    metrics:
      receivers: [docker_stats, nginx, postgresql]
      processors: [batch, resourcedetection/docker]
      exporters: [splunk_hec/metrics]

    logs:
      receivers: [filelog]
      processors: [batch, resourcedetection/system]
      exporters: [splunk_hec/logs]
  
  extensions: [docker_observer]