
receivers:
#======================================
# NGINX TRACES AND METRICS
#======================================
  otlp/traces:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
  nginx:
    endpoint: "http://nginx:11180/status"
    collection_interval: 10s

#======================================
# POSTGRESQL METRICS
#======================================
  postgresql:
    endpoint: db:5432
    username: "${SPLUNK_PSQL_USER}"
    password: "${SPLUNK_PSQL_PASSWORD}"
    databases:
      - gogs
    collection_interval: 10s
    tls:
      insecure: true
      insecure_skip_verify: true 

#======================================
# DOCKER CONTAINERS METRICS
#======================================
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 10s
    timeout: 10s
    metrics:
      container.uptime:
        enabled: true
      container.cpu.usage.system:
        enabled: false
      container.memory.total_rss:
        enabled: true
      container.cpu.utilization:
        enabled: true
      container.memory.percent:
        enabled: true
      container.network.io.usage.rx_bytes:
        enabled: true
      container.network.io.usage.tx_bytes:
        enabled: true
      container.network.io.usage.rx_dropped:
        enabled: true
      container.network.io.usage.tx_dropped:
        enabled: true
      container.memory.usage.limit:
        enabled: true
      container.memory.usage.total:
        enabled: true
      container.blockio.io_service_bytes_recursive:
        enabled: true      

processors:
  batch:
  resourcedetection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]  

exporters:
  splunk_hec/traces:
    token: "${SPLUNK_HEC_TRACES_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
    source: "otel_traces"
    index: "traces"
    tls:
      insecure_skip_verify: true
  splunk_hec/metrics:
    token: "${SPLUNK_HEC_METRICS_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
    source: "otel_metrics"
    index: "metrics"
    tls:
      insecure_skip_verify: true
  splunk_hec/logs:
    token: "${SPLUNK_HEC_LOGS_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
    source: "otel_logs"
    index: "logs"
    tls:
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [otlp/traces]
      processors: [batch, resourcedetection/docker, resourcedetection/system]
      exporters: [splunk_hec/traces]

    metrics:
      receivers: [docker_stats, nginx, postgresql]
      processors: [batch, resourcedetection/docker, resourcedetection/system]
      exporters: [splunk_hec/metrics]

    # logs:
    #   receivers: []
    #   processors: [batch, resourcedetection/system]
    #   exporters: [splunk_hec/logs]

