---
# roles/nfs/defaults/main.yml

# --- Path to the repository directory ---
nfs_export_path: "/srv/gogs-repositories"

# --- Owner and group for this directory ---
nfs_export_owner: "git"
nfs_export_group: "git"
nfs_export_mode: "0755"

# --- Export options (appended to /etc/exports after the path) ---
nfs_export_options: "rw,sync,no_subtree_check,no_root_squash"

# --- User that will operate with the directory ---
nfs_git_user: "git"
nfs_git_user_comment: "Gogs NFS user"

# --- NFS service to start (Ubuntu/Debian) ---
nfs_service_name: "nfs-kernel-server"

# --- Inventory group name for export clients ---
nfs_client_group: "gogs"
