apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  volumeName: database-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
