---
# tasks/db_user_db.yml

- name: Ensure PostgreSQL user '{{ postgres_gogs_user_name }}' exists
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ postgres_gogs_user_name }}"
    password: "{{ postgres_gogs_user_password }}"
    role_attr_flags: CREATEDB

- name: Ensure PostgreSQL database '{{ postgres_gogs_db_name }}' exists
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ postgres_gogs_db_name }}"
    owner: "{{ postgres_gogs_user_name }}"
    state: present