---
# tasks/main.yml

- name: Install PostgreSQL packages
  import_tasks: install.yml

- name: Configure PostgreSQL (deploy templates, gather Gogs IPs)
  import_tasks: configure.yml

- name: Create PostgreSQL user and database
  import_tasks: db_user_db.yml