apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-pvc
spec:
  volumeName: gogs-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi