---
# tasks file for collector
- name: Install a .deb package from the internet
  ansible.builtin.apt:
    deb: "{{ OTEL }}"
  # when: "'splunk-otel-collector' not in ansible_facts.packages"

- name: Ensure config directory exists
  ansible.builtin.file:
    path: /etc/otel/collector/
    state: directory
    owner: splunk-otel-collector
    group: splunk-otel-collector
    mode: "0755"

- name: Deploy custom splunk-otel-collector.conf
  ansible.builtin.template:
    src: splunk-otel-collector.conf.j2
    dest: "/etc/otel/collector/splunk-otel-collector.conf"
    owner: splunk-otel-collector
    group: splunk-otel-collector
  notify: Reload systemd and restart collector

- name: Deploy custom agent_config.yaml
  ansible.builtin.template:
    src: "{{ otel_config_template }}"
    dest: "/etc/otel/collector/agent_config.yaml"
    owner: splunk-otel-collector
    group: splunk-otel-collector
  notify: Reload systemd and restart collector
