---
# vars file for group_vars/psql
# postgres_gogs_user_name: "{{ vault_postgres_gogs_user_name }}"
# postgres_gogs_user_password: "{{ vault_postgres_gogs_user_password }}"
# postgres_gogs_db_name: "{{ vault_postgres_gogs_db_name }}"

postgresql_version: "10"
postgresql_conf_dir: "/etc/postgresql/{{postgresql_version}}/main"
postgresql_conf_file: "{{ postgresql_conf_dir }}/postgresql.conf"
postgresql_hba_file: "{{ postgresql_conf_dir }}/pg_hba.conf"
