---
# roles/otel/defaults/main.yml

# --- variables that must be provided ---
otel_link: "https://github.com/signalfx/splunk-otel-collector/releases/download/v0.126.0/splunk-otel-collector_0.126.0_amd64.deb" # URL to the .deb archive
otel_name: "splunk-otel-collector_0.126.0_amd64.deb" # Name of the .deb file, e.g., "splunk-otel-collector_X.Y.Z_amd64.deb"

splunk_hec_token: "{{ vault_splunk_hec_token }}"
splunk_server_ip: "{{ groups['splunk'][0] }}"
splunk_hec_url: "https://{{ splunk_server_ip }}:8088/services/collector"

# --- Core settings ---
otel_user: "splunk-otel-collector"
otel_group: "splunk-otel-collector"

otel_install_tmp_dir: "/tmp"
otel_install_deb_path: "{{ otel_install_tmp_dir }}/{{ otel_name }}"

otel_config_dir: "/etc/otel/collector"
otel_conf_main: "splunk-otel-collector.conf"
otel_conf_agent: "agent_config.yaml"

# Path to the agent_config template;
# can be a local name in templates/ or an absolute path from variables
otel_agent_config_template: "agent_config_nfs.yaml.j2"

# Name of the systemd service
otel_service_name: "splunk-otel-collector"

# Database credentials
postgres_gogs_db_name: "{{ vault_postgres_gogs_db_name }}"
postgres_gogs_user_name: "{{ vault_postgres_gogs_user_name }}"
postgres_gogs_user_password: "{{ vault_postgres_gogs_user_password }}"
