---
# roles/gogs/tasks/create_user.yml

- name: Ensure group '{{ gogs_group }}' exists
  ansible.builtin.group:
    name: "{{ gogs_group }}"
    state: present

- name: Ensure user '{{ gogs_user }}' exists
  ansible.builtin.user:
    name: "{{ gogs_user }}"
    comment: "{{ gogs_user_comment }}"
    home: "{{ gogs_home_dir }}"
    group: "{{ gogs_group }}"
    create_home: yes
    system: yes
    state: present
