---
# roles/gogs/tasks/download_and_extract.yml

- name: Download Gogs Binary tarball
  ansible.builtin.get_url:
    url: "{{ gogs_tarball }}"
    dest: "{{ gogs_archive_tmp_path }}"
    mode: "0644"
  register: gogs_download

- name: Extract Gogs Binary tarball into {{ gogs_home_dir }}
  ansible.builtin.unarchive:
    src: "{{ gogs_archive_tmp_path }}"
    dest: "{{ gogs_home_dir }}"
    remote_src: yes
    owner: "{{ gogs_user }}"
    group: "{{ gogs_group }}"
