---
# roles/gogs/tasks/main.yml

- name: Validate mandatory variables
  ansible.builtin.assert:
    that:
      - gogs_tarball is defined
      - gogs_tarball | length > 0
    fail_msg: "Змінна 'gogs_tarball' повинна бути визначена (URL до архіву Gogs)."

- name: Create system group and user for Gogs
  import_tasks: create_user.yml

- name: Download and extract Gogs
  import_tasks: download_and_extract.yml

- name: Configure systemd service for Gogs
  import_tasks: configure_systemd.yml

- name: (Optional) Mount NFS for repositories
  import_tasks: install_nfs_client.yml
  when: install_nfs_client

- name: (Optional) Create and mount NFS volume
  import_tasks: mount_nfs.yml
  when: install_nfs_client

- name: Ensure custom configuration directory exists
  import_tasks: setup_custom_conf.yml
