---
# roles/nfs/tasks/create_nfs_directory.yml

- name: Create NFS export directory "{{ nfs_export_path }}"
  ansible.builtin.file:
    path: "{{ nfs_export_path }}"
    state: directory
    owner: "{{ nfs_export_owner }}"
    group: "{{ nfs_export_group }}"
    mode: "{{ nfs_export_mode }}"
