---
# roles/nfs/tasks/generate_exports.yml

- name: Render /etc/exports from template
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload NFS exports