---
# roles/firewall/tasks/main.yml

- name: Ensure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow common SSH port(s)
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ firewall_allowed_common_ports }}"

- name: Allow additional service ports (vars from other roles)
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('tcp') }}"
  loop: "{{ firewall_additional_service_ports | default([]) }}"
  when: firewall_additional_service_ports is defined and firewall_additional_service_ports | length > 0

- name: Enable UFW
  ansible.builtin.command:
    cmd: ufw --force enable
  changed_when: false
  register: ufw_status
  failed_when: ufw_status.rc not in [0, 1]
