---
# handlers file for roles/psql
- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: restarted

- name: Start PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    enabled: yes
    state: started
