---
# roles/otel/tasks/deploy_configs.yml

- name: Deploy main splunk-otel-collector.conf config
  ansible.builtin.template:
    src: "splunk-otel-collector.conf.j2"
    dest: "{{ otel_config_dir }}/{{ otel_conf_main }}"
    owner: "{{ otel_user }}"
    group: "{{ otel_group }}"
    mode: "0644"
  notify: Reload systemd and restart OTel Collector

- name: Deploy agent_config.yaml for OTel Collector
  ansible.builtin.template:
    src: "{{ otel_agent_config_template }}"
    dest: "{{ otel_config_dir }}/{{ otel_conf_agent }}"
    owner: "{{ otel_user }}"
    group: "{{ otel_group }}"
    mode: "0644"
  notify: Reload systemd and restart OTel Collector