---
# roles/otel/tasks/ensure_directories.yml

- name: Ensure OTel config directory exists
  ansible.builtin.file:
    path: "{{ otel_config_dir }}"
    state: directory
    owner: "{{ otel_user }}"
    group: "{{ otel_group }}"
    mode: "0755"