---
# roles/otel/tasks/ensure_user_group.yml

- name: Ensure group for OTel Collector exists
  ansible.builtin.group:
    name: "{{ otel_group }}"
    state: present

- name: Ensure user for OTel Collector exists
  ansible.builtin.user:
    name: "{{ otel_user }}"
    group: "{{ otel_group }}"
    system: yes
    create_home: no
    shell: /usr/sbin/nologin
    state: present
